# PostgreSQL. Versions 8.2 and up are supported.

development:


test:
  # host: adm-demo.cidv375zgkp5.eu-west-1.redshift.amazonaws.com
  adapter:  redshift
  host:     localhost
  encoding: unicode
  database: hsa-billing_test
  pool:     5
  username: hsa
  template: template0

production:
  adapter:  redshift
  host:     localhost
  encoding: unicode
  database: hsa-billing_production
  pool:     5
  username: hsa
  template: template0
