# PostgreSQL. Versions 8.2 and up are supported.

development:


test:
  adapter:  redshift
  host:     localhost
  encoding: unicode
  database: dbtest
  pool:     5
  username: hsa
  template: template0

production:
  adapter:  redshift
  host:     localhost
  encoding: unicode
  database: dbproduction
  pool:     5
  username: hsa
  template: template0
